/* ============================================================
   定价配置的中英两份

   pricing-config.json 是英文版（主语言），pricing-config.zh.json
   是中文版。两份都从中文源生成，保证结构完全一致——结构一旦漂移，
   定价页在某一种语言下就会渲染出空白字段。

   翻译表在下面 T 里。改价格改配置文件本身，改文案改这里。

   命令：node tools/i18n-pricing.js
   ============================================================ */
const fs = require('fs');
const path = require('path');

const REPO = path.resolve(__dirname, '..');
const ZH_SRC = path.join(REPO, 'pricing-config.zh.json');
const EN_OUT = path.join(REPO, 'pricing-config.json');

const T = {
  "个人": "Personal", "家庭": "Family", "户外": "Outdoors", "旅行": "Travel",
  "驾驶": "Driving", "儿童": "Children", "老人": "Elderly care", "宠物": "Pets",
  "庭院": "Garden", "商店": "Retail", "餐厅": "Restaurants", "酒店": "Hotels",
  "展厅": "Showrooms", "工厂": "Factories", "仓库": "Warehouses", "工地": "Construction sites",
  "农场": "Farms", "园区": "Campuses", "机场": "Airports", "港口": "Ports",
  "车站": "Stations", "企业级": "Enterprise", "办公室": "Offices", "工作室": "Studios",
  "商业空间": "Commercial spaces", "工业现场": "Industrial sites",
  "日常生活": "Everyday life", "工作记录": "Work records",
  "储存容量": "Storage", "设备数量": "Devices", "家庭空间": "Family spaces",
  "物流中心": "Logistics centres", "按需报价": "Custom pricing",
  "企业集团": "Corporate groups", "大型物业": "Large properties",
  "扩容储存": "Extra storage", "增加设备": "Additional devices",
  "原始内容": "Original content", "时间线回放": "Timeline replay",
  "端到端加密": "End-to-end encryption", "多节点组网": "Multi-node networking",
  "AI 记忆": "AI Memory", "一个人的日常": "One person's everyday",
  "原始内容保存": "Original content", "本地优先处理": "Local-first processing",
  "一家人的空间": "A family's space", "成员权限分级": "Tiered member permissions",
  "大型户外现场": "Large outdoor sites", "现场断网续传": "Resumable transfer when offline",
  "成规模的部署": "Deployment at scale", "公共基础设施": "Public infrastructure",
  "延长保存周期": "Extended retention", "AI 处理量": "AI processing",
  "AI 记忆保存": "AI Memory", "合规与审计对接": "Compliance and audit integration",
  "开门做生意的地方": "Places open for business",
  "多点位统一时间线": "One timeline across multiple locations",
  "儿童与老人关注模式": "Child and elderly care mode",
  "团队权限与审计日志": "Team permissions and audit logs",
  "Delete 删除": "Delete", "Extend 延长": "Extend",
  "大面积、多节点的现场": "Large, multi-node sites",
  "Archive 归档": "Archive",
  "Edge AI 边缘计算": "Edge AI", "API / SDK 接入": "API / SDK access",
  "专属 SLA 与技术支持": "Dedicated SLA and support",
  "AI Search 语义检索": "AI Search",
  "On-Premise 本地部署": "On-premise deployment",
  "Private Cloud 私有云": "Private cloud",
  "Shared Memory 共享记忆": "Shared Memory",
  "Spatial Memory 空间记忆": "Spatial Memory",
  "原始画面可以过期，对它的理解可以留下来":
    "Raw footage can expire; the understanding drawn from it can stay",
  "Shared Memory 家庭共享记忆": "Shared Memory for families",
  "Advanced Search 高级检索": "Advanced Search",
  "到期后按你的设置处理，画面本身不会永远留着":
    "Handled on expiry according to your settings; the footage itself does not stay forever",
  "最终价格会随 AI 处理量、部署方式和硬件配置浮动，以上为估算。":
    "Final pricing varies with AI processing volume, deployment model and hardware configuration. The above is an estimate.",
  "( 场景基础费 + 储存费 x 保存周期系数 + AI记忆费 + 超出设备数 x 单价 + 超出用户数 x 单价 ) x AI处理量系数":
    "( scene base + storage x retention factor + AI memory fee + extra devices x rate + extra users x rate ) x AI processing multiplier",
};

if (!fs.existsSync(ZH_SRC)) {
  console.log('找不到 pricing-config.zh.json。');
  console.log('第一次跑请先把现有的 pricing-config.json 改名成 pricing-config.zh.json。');
  process.exit(1);
}

const missing = new Set();

/* 只翻值，不翻键；下划线开头的说明字段整段跳过 */
function tr(o) {
  if (typeof o === 'string') {
    if (!/[一-龥]/.test(o)) return o;
    if (T[o] !== undefined) return T[o];
    missing.add(o);
    return o;
  }
  if (Array.isArray(o)) return o.map(tr);
  if (o && typeof o === 'object') {
    const out = {};
    Object.keys(o).forEach((k) => { out[k] = k.startsWith('_') ? o[k] : tr(o[k]); });
    return out;
  }
  return o;
}

const zh = JSON.parse(fs.readFileSync(ZH_SRC, 'utf8'));
const en = tr(zh);
en._comment = 'English pricing config. Generated by tools/i18n-pricing.js from pricing-config.zh.json — edit prices there, edit wording in the tool.';
fs.writeFileSync(EN_OUT, JSON.stringify(en, null, 2) + '\n', 'utf8');

const left = (JSON.stringify(Object.fromEntries(
  Object.entries(en).filter(([k]) => !k.startsWith('_')))).match(/[一-龥]/g) || []).length;

console.log('生成 pricing-config.json（英文）');
console.log('  剩余汉字   ' + left);
if (missing.size) {
  console.log('\n  ⚠ 翻译表里没有的 ' + missing.size + ' 条：');
  [...missing].forEach((s) => console.log('     ' + s));
  process.exitCode = 1;
} else {
  console.log('  ✓ 全部已翻译');
}
